name: run test + push docker image

on:
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: install docker
        uses: docker-practice/actions-setup-docker@master
      - name : run test
        run: ./pypodo_github.sh
      - name: push on docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: thibaultgarcon/pypodo
          tag_with_ref: true
