name: pipeline ci/cd

on:
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

jobs:
  push_to_registry:
    name: run tests + push docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: install python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
      - name: install dependencies python3
        run: |
          python3 -m pip install --upgrade pip3
          pip3 install mutatest coverage pylint colorama termcolor
      - name: pylint
        run: |
          pylint pypodo/__pypodo__.py
        continue-on-error: true       
      - name: pytest
        run: |
          python3 -m unittest -v pypodo/__pypodo__test.py
      - name: mutatest
        run: |
          mutatest 
      - name: coverage
        run: |
          overage run && overage info                 
      - name: install docker
        uses: docker-practice/actions-setup-docker@master
      - name : run test
        run: ./pypodo_github.sh
      - name: push on docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: thibaultgarcon/pypodo
          tag_with_ref: true
